version: '3.7'
networks: 
  network1: 
    external: 
      name: network1
  network2:
    external:
      name: network2

services:
  router1:
    build: 
      context: ./src/Applications
      dockerfile: ./Router1/Dockerfile
    volumes: 
      - .:/dev/cs33031
    networks:
      - network1
      - network2
    environment: 
      TESTVAR: tester123

  router2:
    build: 
      context: ./src/Applications
      dockerfile: ./Router2/Dockerfile
    volumes: 
      - .:/dev/cs33031
    networks:
      - network1
      - network2
    environment: 
      TESTVAR: tester123
    depends_on:
      - router1
