version: '3.7'
networks:
  network1:  
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.11.0/24"
  network2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.22.0/24"
  network3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.33.0/24"
  network4:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.44.0/24"
  network5:  
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.55.0/24"
  network6:  
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.66.0/24"
  network7:  
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.77.0/24"

# networks: 
#   network1:  
#     name: network1
#   network2:
#     name: network2
        
services:
  router1:
    container_name: router1
    volumes: 
      - .:/dev/cs33031
    networks:
      - network1
      - network2
      - network3
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router1
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    depends_on:
      - router2
      - router3

  router2:
    container_name: router2
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router2
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    networks:
      - network3
      - network6
    depends_on:
      - router4

  router3:
    container_name: router3
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router3
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    networks:
      - network2
      - network4
    depends_on:
      - router5

  router4:
    container_name: router4
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router4
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    networks:
      - network6
      - network7
    depends_on:
      - endpointreceiver

  router5:
    container_name: router5
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router5
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    networks:
      - network4
      - network5
    depends_on:
      - router6

  router6:
    container_name: router6
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    environment:
      - name=router6
    command: >
              sh -c "java -cp ../bin Applications.RouterImplementation.RouterImplementation $$name"
    networks:
      - network5
      - network7
    depends_on:
      - endpointreceiver

  endpointsender:
    container_name: endpointsender
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    command: >
              sh -c "java -cp ../bin Applications.EndpointSenderTest.EndpointSenderTest"
    networks:
      - network1
    depends_on:
      - router1

  endpointreceiver:
    container_name: endpointreceiver
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    command: >
              sh -c "java -cp ../bin Applications.EndpointReceiverTest.EndpointReceiverTest"
    networks:
      - network7
    depends_on:
      - controller

  controller:
    container_name: controller
    volumes: 
      - .:/dev/cs33031
    image: openjdk:15
    working_dir: /dev/cs33031/src/
    command: >
              sh -c "java -cp ../bin Applications.ControllerTest.ControllerTest"
    networks:
      - network1
      - network2
      - network3
      - network4
      - network5
      - network6
      - network7
