version: '3.7'
networks: 
  network1:  
    name: network1
  network2:
    name: network2

services:
  router1:
    build: 
      context: ./src/Applications
      dockerfile: ./Router1/Dockerfile
    volumes: 
      - .:/dev/cs33031
    networks:
      - network1
    environment: 
      PORT_R: tester123
    depends_on:
      - router2
  router2:
    build: 
      context: ./src/Applications
      dockerfile: ./Router2/Dockerfile
    volumes: 
      - .:/dev/cs33031
    networks:
      - network1
      - network2
    environment: 
      PORT_R: tester123
