.SILENT:

router1:
	javac Applications/Router1/Router1.java -d ../bin
	java -cp ../bin Applications.Router1.Router1

router2:
	javac Applications/Router2/Router2.java -d ../bin
	java -cp ../bin Applications.Router2.Router2

endpointSender:
	javac Applications/EndpointSenderTest/EndpointSenderTest.java -d ../bin
	java -cp ../bin Applications.EndpointSenderTest.EndpointSenderTest

endpointReceiver:
	javac Applications/EndpointReceiverTest/EndpointReceiverTest.java -d ../bin
	java -cp ../bin Applications.EndpointReceiverTest.EndpointReceiverTest

controller1:
	javac Applications/ControllerTest/ControllerTest.java -d ../bin
	java -cp ../bin Applications.ControllerTest.ControllerTest