.SILENT:

router1:
	javac Applications/Router1/Router1.java -d ../bin
	java -cp ../bin Applications.Router1.Router1

router2:
	javac Applications/Router2/Router2.java -d ../bin
	java -cp ../bin Applications.Router2.Router2